### ISSUE TITLE
It should be "you are welcome to..." instead of "you are welcomed to...".

### ISSUE THREAD

**Issue by Sciroccogti** [doowzs/Class-Forum#2]
["you are welcomed to..."](https://raw.githubusercontent.com/doowzs/Physics-Homework-Forum/master/README.md#contact "README")

[SEE ALSO](http://forum.wordreference.com/threads/you-are-welcome-you-are-welcomed-to.1154775/ "wordreference")

**Comment by doowzs** [comment]
Thanks. Changed to 'welcome'.

> If you have any issues about safety or functions, you are welcome to open an issue to this repository.

See also: [*welcome or welcomed* on grammarly](https://www.grammarly.com/blog/welcome-or-welcomed/)
